export const UPCOMING_MOCK = {
    "data": [
        {
            "away_image_url": "https://img.abiosgaming.com/competitors/Keyd-Stars-new.png",
            "away_team": "Keyd Stars",
            "away_team_id": 1871,
            "best_of": 1,
            "competition_id": 2397,
            "competition_name": "The IQ Option Latin American Cup",
            "displayed_format": "BO1",
            "game_id": 2,
            "game_name": "Counter-Strike",
            "home_image_url": "https://img.abiosgaming.com/competitors/Isurus-Gaming.png",
            "home_team": "Isurus Gaming",
            "home_team_id": 16,
            "id": 339116,
            "live_enabled": true,
            "main_market_id": 11614747,
            "market": {
                "contracts": [
                    {
                        "display_order": 0,
                        "id": 24960387,
                        "market_id": 11614747,
                        "max_bet": "319.00",
                        "name": "Isurus Gaming",
                        "price": "1.52",
                        "raw_status": "open",
                        "status": "open"
                    },
                    {
                        "display_order": 10,
                        "id": 24960388,
                        "market_id": 11614747,
                        "max_bet": "116.00",
                        "name": "Keyd Stars",
                        "price": "2.32",
                        "raw_status": "open",
                        "status": "open"
                    }
                ],
                "display_order": 0,
                "id": 11614747,
                "match_id": 339116,
                "name": "Ganador del encuentro",
                "popular": true,
                "status": "open"
            },
            "name": "Isurus Gaming v Keyd Stars",
            "num_bets_placed": 21,
            "num_markets": 1,
            "start_time": "2021-11-17T01:00:00.000000Z",
            "status": "upcoming",
            "type": "match"
        },
        {
            "away_image_url": "https://img.abiosgaming.com/competitors/Team-oNe-eSports-Logo.png",
            "away_team": "TeamOne",
            "away_team_id": 380,
            "best_of": 3,
            "competition_id": 2474,
            "competition_name": "ESEA Premier Division North America",
            "displayed_format": "BO3",
            "game_id": 2,
            "game_name": "Counter-Strike",
            "home_image_url": "https://d1dewv214im63w.cloudfront.net/teams/strife-logo.png",
            "home_team": "Strife",
            "home_team_id": 14207,
            "id": 344210,
            "live_enabled": false,
            "main_market_id": 11705151,
            "market": {
                "contracts": [
                    {
                        "display_order": 0,
                        "id": 25159626,
                        "market_id": 11705151,
                        "max_bet": "29.00",
                        "name": "Strife",
                        "price": "6.40",
                        "raw_status": "open",
                        "status": "open"
                    },
                    {
                        "display_order": 10,
                        "id": 25159627,
                        "market_id": 11705151,
                        "max_bet": "319.00",
                        "name": "Team One",
                        "price": "1.07",
                        "raw_status": "open",
                        "short_name": "TeamOne",
                        "status": "open"
                    }
                ],
                "display_order": 0,
                "id": 11705151,
                "match_id": 344210,
                "name": "Ganador del encuentro",
                "popular": true,
                "status": "open"
            },
            "name": "Strife v TeamOne",
            "num_bets_placed": 90,
            "num_markets": 8,
            "start_time": "2021-11-17T01:00:00.000000Z",
            "status": "upcoming",
            "type": "match"
        },
        {
            "away_image_url": "https://img.abiosgaming.com/competitors/ATK-Logo.png",
            "away_team": "ATK",
            "away_team_id": 1318,
            "best_of": 3,
            "competition_id": 2474,
            "competition_name": "ESEA Premier Division North America",
            "displayed_format": "BO3",
            "game_id": 2,
            "game_name": "Counter-Strike",
            "home_image_url": "https://s3-eu-west-1.amazonaws.com/midnite.com/teams/placeholder_blue_team.png",
            "home_team": "Team Verum",
            "home_team_id": 15295,
            "id": 344211,
            "live_enabled": false,
            "main_market_id": 11705335,
            "market": {
                "contracts": [
                    {
                        "display_order": 0,
                        "id": 25159997,
                        "market_id": 11705335,
                        "max_bet": "58.00",
                        "name": "Team Verum",
                        "price": "3.60",
                        "raw_status": "open",
                        "status": "halted"
                    },
                    {
                        "display_order": 10,
                        "id": 25159998,
                        "market_id": 11705335,
                        "max_bet": "319.00",
                        "name": "ATK",
                        "price": "1.23",
                        "raw_status": "open",
                        "status": "halted"
                    }
                ],
                "display_order": 0,
                "id": 11705335,
                "match_id": 344211,
                "name": "Ganador del encuentro",
                "popular": true,
                "status": "halted"
            },
            "name": "Team Verum v ATK",
            "num_bets_placed": 99,
            "num_markets": 8,
            "start_time": "2021-11-17T01:00:00.000000Z",
            "status": "upcoming",
            "type": "match"
        },
        {
            "away_image_url": "https://d1dewv214im63w.cloudfront.net/teams/limitless-logo.png",
            "away_team": "Limitless",
            "away_team_id": 15866,
            "best_of": 3,
            "competition_id": 2474,
            "competition_name": "ESEA Premier Division North America",
            "displayed_format": "BO3",
            "game_id": 2,
            "game_name": "Counter-Strike",
            "home_image_url": "https://d1dewv214im63w.cloudfront.net/teams/big-chillin-logo.png",
            "home_team": "Big Chillin",
            "home_team_id": 3674,
            "id": 344212,
            "live_enabled": false,
            "main_market_id": 11705519,
            "market": {
                "contracts": [
                    {
                        "display_order": 0,
                        "id": 25160368,
                        "market_id": 11705519,
                        "max_bet": "116.00",
                        "name": "Big Chillin",
                        "price": "2.42",
                        "raw_status": "open",
                        "status": "open"
                    },
                    {
                        "display_order": 10,
                        "id": 25160369,
                        "market_id": 11705519,
                        "max_bet": "319.00",
                        "name": "Limitless",
                        "price": "1.48",
                        "raw_status": "open",
                        "status": "open"
                    }
                ],
                "display_order": 0,
                "id": 11705519,
                "match_id": 344212,
                "name": "Ganador del encuentro",
                "popular": true,
                "status": "open"
            },
            "name": "Big Chillin v Limitless",
            "num_bets_placed": 63,
            "num_markets": 8,
            "start_time": "2021-11-17T01:00:00.000000Z",
            "status": "upcoming",
            "type": "match"
        },
        {
            "away_image_url": "https://d1dewv214im63w.cloudfront.net/teams/bad-news-bears-320.png",
            "away_team": "Bad News Bears",
            "away_team_id": 293,
            "best_of": 3,
            "competition_id": 2474,
            "competition_name": "ESEA Premier Division North America",
            "displayed_format": "BO3",
            "game_id": 2,
            "game_name": "Counter-Strike",
            "home_image_url": "https://img.abiosgaming.com/competitors/Triumph-gaming-logo.png",
            "home_team": "Triumph",
            "home_team_id": 2599,
            "id": 344213,
            "live_enabled": true,
            "main_market_id": 11705703,
            "market": {
                "contracts": [
                    {
                        "display_order": 0,
                        "id": 25160739,
                        "market_id": 11705703,
                        "max_bet": "29.00",
                        "name": "Triumph",
                        "price": "4.60",
                        "raw_status": "open",
                        "status": "open"
                    },
                    {
                        "display_order": 10,
                        "id": 25160740,
                        "market_id": 11705703,
                        "max_bet": "319.00",
                        "name": "Bad News Bears",
                        "price": "1.15",
                        "raw_status": "open",
                        "status": "open"
                    }
                ],
                "display_order": 0,
                "id": 11705703,
                "match_id": 344213,
                "name": "Ganador del encuentro",
                "popular": true,
                "status": "open"
            },
            "name": "Triumph v Bad News Bears",
            "num_bets_placed": 43,
            "num_markets": 8,
            "start_time": "2021-11-17T01:00:00.000000Z",
            "status": "upcoming",
            "stream_url": "https://player.twitch.tv/?channel=danmarkate",
            "twitch_channel": "danmarkate",
            "type": "match"
        },
        {
            "away_image_url": "https://img.abiosgaming.com/competitors/pain-gaming-teamlogo.png",
            "away_team": "paiN",
            "away_team_id": 616,
            "best_of": 3,
            "competition_id": 2474,
            "competition_name": "ESEA Premier Division North America",
            "displayed_format": "BO3",
            "game_id": 2,
            "game_name": "Counter-Strike",
            "home_image_url": "https://s3-eu-west-1.amazonaws.com/midnite.com/teams/placeholder_blue_team.png",
            "home_team": "Team Eros",
            "home_team_id": 13922,
            "id": 344214,
            "live_enabled": false,
            "main_market_id": 11705887,
            "market": {
                "contracts": [
                    {
                        "display_order": 0,
                        "id": 25161110,
                        "market_id": 11705887,
                        "max_bet": "29.00",
                        "name": "Team Eros",
                        "price": "14.00",
                        "raw_status": "open",
                        "status": "halted"
                    },
                    {
                        "display_order": 10,
                        "id": 25161111,
                        "market_id": 11705887,
                        "max_bet": "319.00",
                        "name": "paiN Gaming",
                        "price": "1.01",
                        "raw_status": "open",
                        "short_name": "paiN",
                        "status": "halted"
                    }
                ],
                "display_order": 0,
                "id": 11705887,
                "match_id": 344214,
                "name": "Ganador del encuentro",
                "popular": true,
                "status": "halted"
            },
            "name": "Team Eros v paiN",
            "num_bets_placed": 78,
            "num_markets": 8,
            "start_time": "2021-11-17T01:00:00.000000Z",
            "status": "upcoming",
            "type": "match"
        },
        {
            "away_image_url": "https://s3-eu-west-1.amazonaws.com/midnite.com/teams/placeholder_red_team.png",
            "away_team": "RBG Esports",
            "away_team_id": 2171,
            "best_of": 3,
            "competition_id": 2474,
            "competition_name": "ESEA Premier Division North America",
            "displayed_format": "BO3",
            "game_id": 2,
            "game_name": "Counter-Strike",
            "home_image_url": "https://d1dewv214im63w.cloudfront.net/teams/extra-salt-logo.png",
            "home_team": "Extra Salt",
            "home_team_id": 9483,
            "id": 344215,
            "live_enabled": false,
            "main_market_id": 11706071,
            "market": {
                "contracts": [
                    {
                        "display_order": 0,
                        "id": 25161481,
                        "market_id": 11706071,
                        "max_bet": "319.00",
                        "name": "Extra Salt",
                        "price": "1.05",
                        "raw_status": "open",
                        "status": "halted"
                    },
                    {
                        "display_order": 10,
                        "id": 25161482,
                        "market_id": 11706071,
                        "max_bet": "29.00",
                        "name": "RBG Esports",
                        "price": "7.60",
                        "raw_status": "open",
                        "status": "halted"
                    }
                ],
                "display_order": 0,
                "id": 11706071,
                "match_id": 344215,
                "name": "Ganador del encuentro",
                "popular": true,
                "status": "halted"
            },
            "name": "Extra Salt v RBG Esports",
            "num_bets_placed": 41,
            "num_markets": 8,
            "start_time": "2021-11-17T01:00:00.000000Z",
            "status": "upcoming",
            "stream_url": "https://player.twitch.tv/?channel=rbg_esports",
            "twitch_channel": "rbg_esports",
            "type": "match"
        },
        {
            "away_image_url": "https://d1dewv214im63w.cloudfront.net/teams/detonate-logo.png",
            "away_team": "Detonate",
            "away_team_id": 14150,
            "best_of": 3,
            "competition_id": 2474,
            "competition_name": "ESEA Premier Division North America",
            "displayed_format": "BO3",
            "game_id": 2,
            "game_name": "Counter-Strike",
            "home_image_url": "https://s3-eu-west-1.amazonaws.com/midnite.com/teams/placeholder_blue_team.png",
            "home_team": "Springroll",
            "home_team_id": 8149,
            "id": 344216,
            "live_enabled": false,
            "main_market_id": 11706255,
            "market": {
                "contracts": [
                    {
                        "display_order": 0,
                        "id": 25161852,
                        "market_id": 11706255,
                        "max_bet": "319.00",
                        "name": "Springroll",
                        "price": "1.42",
                        "raw_status": "open",
                        "status": "open"
                    },
                    {
                        "display_order": 10,
                        "id": 25161853,
                        "market_id": 11706255,
                        "max_bet": "87.00",
                        "name": "Detonate",
                        "price": "2.60",
                        "raw_status": "open",
                        "status": "open"
                    }
                ],
                "display_order": 0,
                "id": 11706255,
                "match_id": 344216,
                "name": "Ganador del encuentro",
                "popular": true,
                "status": "open"
            },
            "name": "Springroll v Detonate",
            "num_bets_placed": 85,
            "num_markets": 8,
            "start_time": "2021-11-17T01:00:00.000000Z",
            "status": "upcoming",
            "stream_url": "https://player.twitch.tv/?channel=detonatv",
            "twitch_channel": "detonatv",
            "type": "match"
        },
        {
            "away_image_url": "https://img.abiosgaming.com/flags/Vietnam.png",
            "away_team": "Vietnam",
            "away_team_id": 2787,
            "best_of": 2,
            "competition_id": 2478,
            "competition_name": "SEAEF Dota2 Championship",
            "displayed_format": "BO2",
            "game_id": 1,
            "game_name": "Dota 2",
            "home_image_url": "https://img.abiosgaming.com/flags/Philippines.png",
            "home_team": "Philippines",
            "home_team_id": 2791,
            "id": 345736,
            "live_enabled": false,
            "main_market_id": 11736379,
            "market": {
                "contracts": [
                    {
                        "display_order": 0,
                        "id": 25224831,
                        "market_id": 11736379,
                        "max_bet": "145.00",
                        "name": "Philippines",
                        "price": "1.54",
                        "raw_status": "open",
                        "status": "open"
                    },
                    {
                        "display_order": 10,
                        "id": 25224832,
                        "market_id": 11736379,
                        "max_bet": "29.00",
                        "name": "Draw",
                        "price": "2.50",
                        "raw_status": "open",
                        "status": "open"
                    },
                    {
                        "display_order": 20,
                        "id": 25224833,
                        "market_id": 11736379,
                        "max_bet": "29.00",
                        "name": "Vietnam",
                        "price": "8.40",
                        "raw_status": "open",
                        "status": "open"
                    }
                ],
                "display_order": 2,
                "id": 11736379,
                "match_id": 345736,
                "name": "Match Winner (3 Way)",
                "popular": true,
                "status": "open"
            },
            "name": "Philippines v Vietnam",
            "num_bets_placed": 80,
            "num_markets": 6,
            "start_time": "2021-11-17T07:00:00.000000Z",
            "status": "upcoming",
            "type": "match"
        },
        {
            "away_image_url": "https://img.abiosgaming.com/flags/Malaysia.png",
            "away_team": "Malaysia",
            "away_team_id": 2786,
            "best_of": 2,
            "competition_id": 2478,
            "competition_name": "SEAEF Dota2 Championship",
            "displayed_format": "BO2",
            "game_id": 1,
            "game_name": "Dota 2",
            "home_image_url": "https://img.abiosgaming.com/flags/Thailand.png",
            "home_team": "Thailand",
            "home_team_id": 2789,
            "id": 345737,
            "live_enabled": false,
            "main_market_id": 11736407,
            "market": {
                "contracts": [
                    {
                        "display_order": 0,
                        "id": 25224889,
                        "market_id": 11736407,
                        "max_bet": "145.00",
                        "name": "Thailand",
                        "price": "1.15",
                        "raw_status": "open",
                        "status": "open"
                    },
                    {
                        "display_order": 10,
                        "id": 25224890,
                        "market_id": 11736407,
                        "max_bet": "29.00",
                        "name": "Draw",
                        "price": "4.40",
                        "raw_status": "open",
                        "status": "open"
                    },
                    {
                        "display_order": 20,
                        "id": 25224891,
                        "market_id": 11736407,
                        "max_bet": "29.00",
                        "name": "Malaysia",
                        "price": "14.50",
                        "raw_status": "open",
                        "status": "open"
                    }
                ],
                "display_order": 2,
                "id": 11736407,
                "match_id": 345737,
                "name": "Match Winner (3 Way)",
                "popular": true,
                "status": "open"
            },
            "name": "Thailand v Malaysia",
            "num_bets_placed": 25,
            "num_markets": 6,
            "start_time": "2021-11-17T07:00:00.000000Z",
            "status": "upcoming",
            "type": "match"
        },
        {
            "away_image_url": "https://img.abiosgaming.com/competitors/LGD-Gaming2017.png",
            "away_team": "LGD",
            "away_team_id": 412,
            "best_of": 1,
            "competition_id": 2445,
            "competition_name": "National Electronic Sports Tournament",
            "displayed_format": "BO1",
            "game_id": 4,
            "game_name": "League of Legends",
            "home_image_url": "https://img.abiosgaming.com/competitors/Bilibili-gaming-LPL-LOgo.png",
            "home_team": "Bilibili Gaming",
            "home_team_id": 426,
            "id": 339558,
            "live_enabled": true,
            "main_market_id": 11626211,
            "market": {
                "contracts": [
                    {
                        "display_order": 0,
                        "id": 24983059,
                        "market_id": 11626211,
                        "max_bet": "261.00",
                        "name": "Bilibili Gaming",
                        "price": "1.47",
                        "raw_status": "open",
                        "status": "open"
                    },
                    {
                        "display_order": 10,
                        "id": 24983060,
                        "market_id": 11626211,
                        "max_bet": "87.00",
                        "name": "LGD Gaming",
                        "price": "2.40",
                        "raw_status": "open",
                        "short_name": "LGD",
                        "status": "open"
                    }
                ],
                "display_order": 0,
                "id": 11626211,
                "match_id": 339558,
                "name": "Ganador del encuentro",
                "popular": true,
                "status": "open"
            },
            "name": "Bilibili Gaming v LGD",
            "num_bets_placed": 47,
            "num_markets": 7,
            "start_time": "2021-11-17T07:00:00.000000Z",
            "status": "upcoming",
            "type": "match"
        },
        {
            "away_image_url": "https://s3-eu-west-1.amazonaws.com/midnite.com/teams/placeholder_red_team.png",
            "away_team": "Enigma Gaming",
            "away_team_id": 13721,
            "best_of": 3,
            "competition_id": 2476,
            "competition_name": "The Esports Club Showdown",
            "displayed_format": "BO3",
            "game_id": 22,
            "game_name": "Valorant",
            "home_image_url": "https://d1dewv214im63w.cloudfront.net/teams/bleed-logo.png",
            "home_team": "Bleed eSports",
            "home_team_id": 14602,
            "id": 346341,
            "live_enabled": false,
            "main_market_id": 11750865,
            "market": {
                "contracts": [
                    {
                        "display_order": 0,
                        "id": 25256562,
                        "market_id": 11750865,
                        "max_bet": "232.00",
                        "name": "Bleed eSports",
                        "price": "1.28",
                        "raw_status": "open",
                        "status": "open"
                    },
                    {
                        "display_order": 10,
                        "id": 25256563,
                        "market_id": 11750865,
                        "max_bet": "29.00",
                        "name": "Enigma Gaming",
                        "price": "3.20",
                        "raw_status": "open",
                        "status": "open"
                    }
                ],
                "display_order": 0,
                "id": 11750865,
                "match_id": 346341,
                "name": "Ganador del encuentro",
                "popular": true,
                "status": "open"
            },
            "name": "Bleed eSports v Enigma Gaming",
            "num_bets_placed": 75,
            "num_markets": 8,
            "start_time": "2021-11-17T07:30:00.000000Z",
            "status": "upcoming",
            "type": "match"
        },
        {
            "away_image_url": "https://img.abiosgaming.com/competitors/JD-Gaming.png",
            "away_team": "JD Gaming",
            "away_team_id": 77,
            "best_of": 1,
            "competition_id": 2445,
            "competition_name": "National Electronic Sports Tournament",
            "displayed_format": "BO1",
            "game_id": 4,
            "game_name": "League of Legends",
            "home_image_url": "https://img.abiosgaming.com/competitors/V5-Victory-five-LPL.png",
            "home_team": "Victory Five",
            "home_team_id": 78,
            "id": 339568,
            "live_enabled": true,
            "main_market_id": 11626507,
            "market": {
                "contracts": [
                    {
                        "display_order": 0,
                        "id": 24983660,
                        "market_id": 11626507,
                        "max_bet": "145.00",
                        "name": "Victory Five",
                        "price": "1.87",
                        "raw_status": "open",
                        "status": "open"
                    },
                    {
                        "display_order": 10,
                        "id": 24983661,
                        "market_id": 11626507,
                        "max_bet": "174.00",
                        "name": "JD Gaming",
                        "price": "1.77",
                        "raw_status": "open",
                        "status": "open"
                    }
                ],
                "display_order": 0,
                "id": 11626507,
                "match_id": 339568,
                "name": "Ganador del encuentro",
                "popular": true,
                "status": "open"
            },
            "name": "Victory Five v JD Gaming",
            "num_bets_placed": 33,
            "num_markets": 7,
            "start_time": "2021-11-17T08:00:00.000000Z",
            "status": "upcoming",
            "type": "match"
        },
        {
            "away_image_url": "https://img.abiosgaming.com/flags/Thailand.png",
            "away_team": "Thailand",
            "away_team_id": 2789,
            "best_of": 2,
            "competition_id": 2478,
            "competition_name": "SEAEF Dota2 Championship",
            "displayed_format": "BO2",
            "game_id": 1,
            "game_name": "Dota 2",
            "home_image_url": "https://img.abiosgaming.com/flags/Myanmar.png",
            "home_team": "Myanmar",
            "home_team_id": 2792,
            "id": 345738,
            "live_enabled": false,
            "main_market_id": 11736435,
            "market": {
                "contracts": [
                    {
                        "display_order": 0,
                        "id": 25224947,
                        "market_id": 11736435,
                        "max_bet": "29.00",
                        "name": "Myanmar",
                        "price": "5.40",
                        "raw_status": "open",
                        "status": "open"
                    },
                    {
                        "display_order": 10,
                        "id": 25224948,
                        "market_id": 11736435,
                        "max_bet": "58.00",
                        "name": "Draw",
                        "price": "2.06",
                        "raw_status": "open",
                        "status": "open"
                    },
                    {
                        "display_order": 20,
                        "id": 25224949,
                        "market_id": 11736435,
                        "max_bet": "58.00",
                        "name": "Thailand",
                        "price": "2.02",
                        "raw_status": "open",
                        "status": "open"
                    }
                ],
                "display_order": 2,
                "id": 11736435,
                "match_id": 345738,
                "name": "Match Winner (3 Way)",
                "popular": true,
                "status": "open"
            },
            "name": "Myanmar v Thailand",
            "num_bets_placed": 98,
            "num_markets": 6,
            "start_time": "2021-11-17T09:00:00.000000Z",
            "status": "upcoming",
            "type": "match"
        },
        {
            "away_image_url": "https://s3-eu-west-1.amazonaws.com/midnite.com/teams/placeholder_red_team.png",
            "away_team": "Apocalypse",
            "away_team_id": 15304,
            "best_of": 3,
            "competition_id": 2381,
            "competition_name": "ESEA Premier Australia",
            "displayed_format": "BO3",
            "game_id": 2,
            "game_name": "Counter-Strike",
            "home_image_url": "https://d1dewv214im63w.cloudfront.net/teams/caught-off-guard-logo.png",
            "home_team": "Caught off Guard",
            "home_team_id": 7514,
            "id": 342358,
            "live_enabled": false,
            "main_market_id": 11674356,
            "market": {
                "contracts": [
                    {
                        "display_order": 0,
                        "id": 25092117,
                        "market_id": 11674356,
                        "max_bet": "319.00",
                        "name": "Caught off Guard",
                        "price": "1.23",
                        "raw_status": "open",
                        "status": "open"
                    },
                    {
                        "display_order": 10,
                        "id": 25092118,
                        "market_id": 11674356,
                        "max_bet": "58.00",
                        "name": "Apocalypse",
                        "price": "3.60",
                        "raw_status": "open",
                        "status": "open"
                    }
                ],
                "display_order": 0,
                "id": 11674356,
                "match_id": 342358,
                "name": "Ganador del encuentro",
                "popular": true,
                "status": "open"
            },
            "name": "Caught off Guard v Apocalypse",
            "num_bets_placed": 38,
            "num_markets": 7,
            "start_time": "2021-11-17T09:00:00.000000Z",
            "status": "upcoming",
            "type": "match"
        },
        {
            "away_image_url": "https://d1dewv214im63w.cloudfront.net/teams/kanga-esports-logo.png",
            "away_team": "Kanga Esports",
            "away_team_id": 13573,
            "best_of": 3,
            "competition_id": 2381,
            "competition_name": "ESEA Premier Australia",
            "displayed_format": "BO3",
            "game_id": 2,
            "game_name": "Counter-Strike",
            "home_image_url": "https://img.abiosgaming.com/competitors/Paradox-gaming-logo.png",
            "home_team": "Paradox",
            "home_team_id": 589,
            "id": 342360,
            "live_enabled": false,
            "main_market_id": 11674725,
            "market": {
                "contracts": [
                    {
                        "display_order": 0,
                        "id": 25092860,
                        "market_id": 11674725,
                        "max_bet": "319.00",
                        "name": "Paradox",
                        "price": "1.01",
                        "raw_status": "open",
                        "status": "open"
                    },
                    {
                        "display_order": 10,
                        "id": 25092861,
                        "market_id": 11674725,
                        "max_bet": "29.00",
                        "name": "Kanga Esports",
                        "price": "12.50",
                        "raw_status": "open",
                        "status": "open"
                    }
                ],
                "display_order": 0,
                "id": 11674725,
                "match_id": 342360,
                "name": "Ganador del encuentro",
                "popular": true,
                "status": "open"
            },
            "name": "Paradox v Kanga Esports",
            "num_bets_placed": 58,
            "num_markets": 7,
            "start_time": "2021-11-17T09:00:00.000000Z",
            "status": "upcoming",
            "type": "match"
        },
        {
            "away_image_url": "https://img.abiosgaming.com/competitors/LNG-LINING-ESPORTS-logo.png",
            "away_team": "LNG Esports",
            "away_team_id": 1634,
            "best_of": 1,
            "competition_id": 2445,
            "competition_name": "National Electronic Sports Tournament",
            "displayed_format": "BO1",
            "game_id": 4,
            "game_name": "League of Legends",
            "home_image_url": "https://img.abiosgaming.com/competitors/Invictus-Gaming-iG-black.png",
            "home_team": "Invictus",
            "home_team_id": 427,
            "id": 339582,
            "live_enabled": true,
            "main_market_id": 11627279,
            "market": {
                "contracts": [
                    {
                        "display_order": 0,
                        "id": 24985387,
                        "market_id": 11627279,
                        "max_bet": "232.00",
                        "name": "Invictus Gaming",
                        "price": "1.60",
                        "raw_status": "open",
                        "short_name": "Invictus",
                        "status": "open"
                    },
                    {
                        "display_order": 10,
                        "id": 24985388,
                        "market_id": 11627279,
                        "max_bet": "116.00",
                        "name": "LNG Esports",
                        "price": "2.10",
                        "raw_status": "open",
                        "status": "open"
                    }
                ],
                "display_order": 0,
                "id": 11627279,
                "match_id": 339582,
                "name": "Ganador del encuentro",
                "popular": true,
                "status": "open"
            },
            "name": "Invictus v LNG Esports",
            "num_bets_placed": 67,
            "num_markets": 7,
            "start_time": "2021-11-17T09:00:00.000000Z",
            "status": "upcoming",
            "type": "match"
        },
        {
            "away_image_url": "https://s3-eu-west-1.amazonaws.com/midnite.com/teams/placeholder_red_team.png",
            "away_team": "Luxury Esports",
            "away_team_id": 8567,
            "best_of": 3,
            "competition_id": 2465,
            "competition_name": "Vietnam Championship Series",
            "displayed_format": "BO3",
            "game_id": 4,
            "game_name": "League of Legends",
            "home_image_url": "https://d1dewv214im63w.cloudfront.net/teams/burst-the-sky-logo.png",
            "home_team": "Burst The Sky",
            "home_team_id": 9429,
            "id": 341847,
            "live_enabled": true,
            "main_market_id": 11664740,
            "market": {
                "contracts": [
                    {
                        "display_order": 0,
                        "id": 25067208,
                        "market_id": 11664740,
                        "max_bet": "174.00",
                        "name": "Burst The Sky",
                        "price": "1.77",
                        "raw_status": "open",
                        "status": "open"
                    },
                    {
                        "display_order": 10,
                        "id": 25067209,
                        "market_id": 11664740,
                        "max_bet": "145.00",
                        "name": "Luxury Esports",
                        "price": "1.87",
                        "raw_status": "open",
                        "status": "open"
                    }
                ],
                "display_order": 0,
                "id": 11664740,
                "match_id": 341847,
                "name": "Ganador del encuentro",
                "popular": true,
                "status": "open"
            },
            "name": "Burst The Sky v Luxury Esports",
            "num_bets_placed": 49,
            "num_markets": 26,
            "start_time": "2021-11-17T09:00:00.000000Z",
            "status": "upcoming",
            "stream_url": "https://player.twitch.tv/?channel=vcsenglish",
            "twitch_channel": "vcsenglish",
            "type": "match"
        },
        {
            "away_image_url": "https://d1dewv214im63w.cloudfront.net/teams/bren-logo.png",
            "away_team": "Bren Esports",
            "away_team_id": 7846,
            "best_of": 2,
            "competition_id": 2420,
            "competition_name": "Epulze Royal SEA Challenge",
            "displayed_format": "BO2",
            "game_id": 22,
            "game_name": "Valorant",
            "home_image_url": "https://s3-eu-west-1.amazonaws.com/midnite.com/teams/placeholder_blue_team.png",
            "home_team": "Paper Rex",
            "home_team_id": 10618,
            "id": 339894,
            "live_enabled": true,
            "main_market_id": 11636639,
            "market": {
                "contracts": [
                    {
                        "display_order": 0,
                        "id": 25007639,
                        "market_id": 11636639,
                        "max_bet": "116.00",
                        "name": "Paper Rex",
                        "price": "1.92",
                        "raw_status": "open",
                        "status": "open"
                    },
                    {
                        "display_order": 10,
                        "id": 25007640,
                        "market_id": 11636639,
                        "max_bet": "87.00",
                        "name": "Draw",
                        "price": "2.14",
                        "raw_status": "open",
                        "status": "open"
                    },
                    {
                        "display_order": 20,
                        "id": 25007641,
                        "market_id": 11636639,
                        "max_bet": "29.00",
                        "name": "Bren Esports",
                        "price": "6.00",
                        "raw_status": "open",
                        "status": "open"
                    }
                ],
                "display_order": 2,
                "id": 11636639,
                "match_id": 339894,
                "name": "Match Winner (3 Way)",
                "popular": true,
                "status": "open"
            },
            "name": "Paper Rex v Bren Esports",
            "num_bets_placed": 17,
            "num_markets": 6,
            "start_time": "2021-11-17T09:00:00.000000Z",
            "status": "upcoming",
            "type": "match"
        }
    ],
    "filters": {

    },
    "page": 0,
    "page_size": 20,
    "pages": 7
}